/**
 * Centralised data for ContentPage-driven landing pages.
 * Each entry defines the props for one route.
 * Imported by App.tsx (for routing) AND scripts/postbuild.ts (for pre-render SEO).
 */

import type { ContentPageProps } from './ContentPage';

const baseSchema = (slug: string, title: string, description: string, breadcrumbName: string) => ([
  {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    '@id': `https://mychef.id/${slug}#webpage`,
    url: `https://mychef.id/${slug}`,
    name: title,
    description,
    isPartOf: { '@id': 'https://mychef.id/#website' },
    about: { '@id': 'https://mychef.id/#organization' },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://mychef.id/' },
      { '@type': 'ListItem', position: 2, name: breadcrumbName, item: `https://mychef.id/${slug}` },
    ],
  },
]);

export const CONTENT_PAGES: Record<string, ContentPageProps & { slug: string }> = {
  retreats: {
    slug: 'retreats',
    canonical: 'https://mychef.id/retreats',
    title: 'Private Chef for Retreats in Bali — Yoga, Wellness, Corporate | myCHEF',
    description: 'Background-checked private chefs for yoga retreats, wellness retreats, and corporate offsites in Bali. Custom meal plans, dietary-restricted menus, on-site cooking for 8-50 guests.',
    keywords: 'private chef retreat bali, yoga retreat chef, wellness retreat catering bali, corporate offsite bali, retreat chef indonesia, yoga teacher training catering',
    h1: 'Private Chef for Retreats in Bali',
    lead: "Background-checked private chefs for yoga retreats, wellness retreats, corporate offsites, and yoga teacher trainings across Bali. Custom meal plans, full dietary-restriction support (vegan, gluten-free, halal, kosher), and on-site cooking for groups of 8 to 50 guests.",
    sections: [
      { heading: 'Types of retreats we cater', bullets: [
        'Yoga retreats — vegan / plant-based menus, kapha-vata-pitta balancing on request, kitchari + dosa breakfasts, juice cleanses',
        'Wellness retreats — anti-inflammatory menus, no refined sugar, organic farm-to-table from Tegallalang and Tabanan',
        'Yoga teacher trainings (YTT) — 10-30 days, 3 meals/day, recurring weekly menu plans with cost-controlled ingredient budgets',
        'Corporate offsites — multi-course tasting dinners, breakfast buffets for 30+ pax, working lunches plated for productivity',
        'Surf camps + adventure retreats — high-energy meals, protein-forward, easy on the kitchen between sessions',
      ]},
      { heading: 'What\'s included for retreat bookings', bullets: [
        'Custom multi-day menu plan reviewed with retreat host before the program',
        'Single chef or chef team (we scale to group size — 1 chef per 10-15 guests is standard)',
        'Ingredient sourcing from organic farms across Bali; transparent cost pass-through',
        'Kitchen setup + plating + serving + cleanup for every meal',
        'Dietary restriction handling at the per-guest level (allergens, vegan, halal, kosher, low-carb, paleo)',
        'Operations team available on WhatsApp throughout the retreat',
      ]},
      { heading: 'Pricing for retreat chef placements', body: "Pricing depends on duration, guest count, meal frequency, and venue location. Multi-day retreats (3+ days) typically range Rp 1.5M-3M per chef per day plus ingredients at cost. For 10-day YTT programs with 3 meals/day for 20 guests, expect Rp 350k-550k per guest per day all-in. WhatsApp +62 822-3756-5997 with your dates and program size for a custom quote." },
      { heading: 'How retreat bookings work', steps: [
        { title: 'Tell us the program', description: 'Dates, guest count, dietary restrictions, venue location, any specific cuisine direction (Mediterranean / vegan / Balinese / mixed).' },
        { title: 'Menu draft + chef profile', description: 'We send a sample week of menus and the chef\'s background within 24 hours. You review and adjust before committing.' },
        { title: 'Deposit + lock in', description: '50% deposit reserves the chef for your dates. Final balance + ingredient cost reconciliation due on the final day of the retreat.' },
        { title: 'Run the retreat', description: 'Chef arrives the day before, sets up kitchen workflow with venue staff, cooks all meals on schedule. You focus on programming.' },
      ]},
      { heading: 'Retreat venues we know well', body: 'Most retreats book chefs into private villa compounds in Ubud, Canggu, Pererenan, and Uluwatu. We have working knowledge of villa kitchens at venues across Tegallalang, Ubud (Penestanan, Sayan), Canggu (Pererenan, Berawa, Echo Beach), and the Bukit peninsula. If your venue is new to us, the chef arrives a day early to test the kitchen workflow.' },
    ],
    ctaSource: 'experience',
    ctaPresetOpts: { message: "Hi myCHEF — interested in a private chef for our retreat in Bali. Dates: [start]-[end], [N] guests, [yoga/wellness/corporate/YTT]. Can you send a sample menu plan?" },
    ctaLabel: 'WhatsApp about a retreat',
    secondaryCta: { label: 'Custom quote form', href: '/quote' },
    structuredData: [
      ...baseSchema('retreats', 'Private Chef for Retreats in Bali — Yoga, Wellness, Corporate | myCHEF', 'Background-checked private chefs for yoga retreats, wellness retreats, and corporate offsites in Bali.', 'Retreats'),
      {
        '@context': 'https://schema.org',
        '@type': 'Service',
        '@id': 'https://mychef.id/retreats#service',
        name: 'Private Chef for Retreats — Bali',
        serviceType: 'Multi-day private chef placement for retreats',
        description: 'Recurring meal preparation for yoga, wellness, corporate, and YTT retreats across Bali. Single chef or chef team scaled to group size.',
        provider: { '@id': 'https://mychef.id/#organization' },
        areaServed: { '@type': 'AdministrativeArea', name: 'Bali, Indonesia' },
        offers: { '@type': 'Offer', priceCurrency: 'IDR', price: '1500000', description: 'From Rp 1.5M per chef per day plus ingredients at cost' },
      },
    ],
  },

  catering: {
    slug: 'catering',
    canonical: 'https://mychef.id/catering',
    title: 'Best Catering in Bali — Private Chef at Home | myCHEF Indonesia',
    description: 'Looking for the best catering in Bali? myCHEF puts a private chef in your villa kitchen — fresher than catering, fully custom, all-in pricing. From Rp 800k/hr. WhatsApp booking.',
    keywords: 'best catering bali, catering bali villa, private catering bali, in-villa catering bali, bali wedding catering, bali event catering, alternative to catering bali',
    h1: 'Catering in Bali — Why a Private Chef Beats Traditional Catering',
    lead: 'Most people searching for "catering in Bali" actually want fresh, custom-cooked food in their villa — not pre-made trays delivered cold from a kitchen across town. myCHEF Indonesia is the alternative: a background-checked private chef cooks in your villa kitchen, plates and serves the food, and cleans up before leaving. Same final result as a private restaurant in your home, no industrial catering trays involved.',
    sections: [
      { heading: 'Private chef vs catering company — what\'s different', bullets: [
        'Cooked on the spot in YOUR kitchen, not driven over in foil trays. Fresh, not warm-held.',
        'Menu is built around your guests, dietary restrictions, and what\'s freshest in the market that morning.',
        'Chef can adjust real-time — picky kid, surprise vegan friend, wine cue from the host? Handled.',
        'Chef plates each course directly to your guests like a restaurant. No buffet table required.',
        'Cleanup is included. Your kitchen comes back the way it was.',
        'Pricing is per-hour + ingredients at cost — no markup on food, no minimum order trays.',
      ]},
      { heading: 'When traditional catering still makes sense', body: 'Catering wins on volume — for 100+ guests, a catering operation has the kitchen capacity that a single private chef can\'t match. For 4-20 guests, the private chef model wins on freshness, customisation, and total cost-per-guest (no catering minimums, no service charge markup). For 20-50 guests we run a chef team — same in-villa model, scaled up.' },
      { heading: 'What myCHEF delivers in place of "catering"', bullets: [
        'Single-night villa dinners for 4-20 guests (most common)',
        'Wedding rehearsal dinners and small wedding ceremonies (up to 30 guests)',
        'Birthday + anniversary + proposal dinners',
        'Corporate offsite dinners + multi-day retreat catering',
        'Recurring weekly meal-prep for expat families',
        'Full-time household chef placement',
      ]},
      { heading: 'Pricing comparison', body: 'A traditional Bali catering company for 6 guests typically quotes Rp 750k-1.2M per guest (8-course tasting), or Rp 4.5M-7M total — with most of the budget going to service charges, transport, and packaging. myCHEF private chef for the same 6 guests: Rp 800k/hr × 4 hours (chef fee) + ingredients at cost = Rp 3.5M-4.5M total. Same quality food, lower price, fresher result.' },
      { heading: 'Common cuisines we cater', body: 'Mediterranean, modern European, Asian fusion, traditional Balinese, vegan + plant-based, halal-certified, gluten-free, and any combination. See sample menus per cuisine.' },
    ],
    ctaSource: 'experience',
    ctaPresetOpts: { message: "Hi myCHEF — comparing private chef vs traditional catering for our event in Bali. Date: [date], [N] guests, [area]. Can you send pricing?" },
    ctaLabel: 'WhatsApp about catering',
    secondaryCta: { label: 'See sample menus', href: '/menus' },
    structuredData: [
      ...baseSchema('catering', 'Best Catering in Bali — Private Chef at Home | myCHEF Indonesia', 'Looking for the best catering in Bali? myCHEF puts a private chef in your villa kitchen.', 'Catering'),
      {
        '@context': 'https://schema.org',
        '@type': 'Service',
        '@id': 'https://mychef.id/catering#service',
        name: 'In-Villa Catering Alternative — Bali',
        serviceType: 'Private chef catering for Bali villas and events',
        provider: { '@id': 'https://mychef.id/#organization' },
        areaServed: { '@type': 'AdministrativeArea', name: 'Bali, Indonesia' },
        offers: { '@type': 'Offer', priceCurrency: 'IDR', price: '800000', description: 'From Rp 800,000 per hour, 3-hour minimum + ingredients at cost' },
      },
    ],
  },

  'proposal-dinner': {
    slug: 'proposal-dinner',
    canonical: 'https://mychef.id/proposal-dinner',
    title: 'Proposal Dinner in Bali — Private Chef + Sommelier | myCHEF Indonesia',
    description: 'Plan a private proposal dinner in your Bali villa with myCHEF. Multi-course menu, sommelier wine pairing, candle + flower setup, photographer coordination. From Rp 6M for 2 guests.',
    keywords: 'proposal dinner bali, marriage proposal bali, private proposal chef bali, surprise proposal dinner bali, propose at villa bali, romantic proposal dinner',
    h1: 'Private Proposal Dinner in a Bali Villa',
    lead: "Booking a private chef for your Bali proposal is the highest-stakes booking we do — the dinner only happens once, and every detail has to land. myCHEF has handled 100+ proposal dinners since 2012: villa terrace candle setups, multi-course tasting menus with sommelier-paired wines, ring-on-the-plate reveals coordinated with the photographer, surprise cake courses, and the discreet operations crew that keeps the surprise intact.",
    sections: [
      { heading: 'What a myCHEF proposal dinner includes', bullets: [
        '5-course tasting menu built around their favorite cuisines and ingredients',
        'Sommelier-paired wine flight (4 wines, one per course + amuse-bouche)',
        'Villa terrace or beachfront setup: candles, fresh flowers, linens, ambient lighting',
        'Coordinated playlist (your shared songs, first dance song, anniversary track)',
        'Discreet coordination with your proposal photographer + ring delivery onto the plate',
        'Surprise course: a custom proposal cake or shared dessert with the ring nested in',
        'Operations team on WhatsApp throughout — silent until you need us',
      ]},
      { heading: 'How the proposal gets planned', steps: [
        { title: 'Tell us the story', description: 'Their favorite cuisines, allergies, the venue, the proposal moment (sunset, after dessert, during cocktails), and what they\'d most enjoy.' },
        { title: 'Menu + setup mock-up', description: 'We send a draft menu and a photo-realistic setup mock-up within 48 hours. You adjust until it\'s perfect.' },
        { title: 'Photographer + florist coordination', description: 'If you\'re using your own photographer, we sync schedules. If you need recommendations, we have trusted partners.' },
        { title: 'The night itself', description: 'Chef arrives 3-4 hours early. Setup is done before your arrival. Sommelier paces the wines to your conversation. The proposal moment is yours.' },
      ]},
      { heading: 'Pricing for proposal dinners', body: 'From Rp 6M for 2 guests, all-in. Includes 5-course tasting menu, sommelier with 4-wine flight, candle + flower setup, custom playlist coordination, photographer logistics, and the surprise cake course. Add-ons: live string player (Rp 2.5M-4M), additional florist (Rp 1.5M-3M), professional photographer (Rp 4M-8M depending on coverage).' },
      { heading: 'Where proposals happen', body: 'Most myCHEF proposals are villa terrace dinners — Canggu rice-field views, Seminyak rooftops, Uluwatu cliff villas, Ubud jungle decks. We also do beachfront setups in Jimbaran, Nusa Dua, and Lovina. The villa kitchen needs basic equipment; everything else we bring.' },
    ],
    ctaSource: 'experience',
    ctaPresetOpts: { message: "Hi myCHEF — planning a surprise proposal dinner in Bali. Date: [date], area: [Canggu/Seminyak/Ubud/Uluwatu/other], any specific cuisines or ideas: [...]. Need full discretion." },
    ctaLabel: 'WhatsApp about a proposal',
    secondaryCta: { label: 'See sample menus', href: '/menus' },
    structuredData: [
      ...baseSchema('proposal-dinner', 'Proposal Dinner in Bali — Private Chef + Sommelier | myCHEF Indonesia', 'Plan a private proposal dinner in your Bali villa with myCHEF.', 'Proposal Dinner'),
      {
        '@context': 'https://schema.org',
        '@type': 'Service',
        '@id': 'https://mychef.id/proposal-dinner#service',
        name: 'Proposal Dinner in Bali',
        serviceType: 'Private chef proposal dinner with sommelier + setup',
        provider: { '@id': 'https://mychef.id/#organization' },
        areaServed: { '@type': 'AdministrativeArea', name: 'Bali, Indonesia' },
        offers: { '@type': 'Offer', priceCurrency: 'IDR', price: '6000000', description: 'From Rp 6M for 2 guests all-in (5-course tasting + sommelier + setup)' },
      },
    ],
  },

  'honeymoon-chef': {
    slug: 'honeymoon-chef',
    canonical: 'https://mychef.id/honeymoon-chef',
    title: 'Honeymoon Private Chef in Bali — Villa Dining for Two | myCHEF',
    description: 'Hire a private chef for your Bali honeymoon. Romantic multi-course dinners, sommelier wine pairing, candle + flower villa setup. WhatsApp booking from Rp 4.5M for 2 guests.',
    keywords: 'honeymoon chef bali, bali honeymoon private dinner, romantic chef bali, honeymoon villa dinner bali, honeymoon dinner ubud, honeymoon dinner seminyak',
    h1: 'Honeymoon Private Chef in Bali',
    lead: "myCHEF has been cooking honeymoon dinners in Bali villas since 2012. We know which villas have the best sunset views, which beaches do candle setups, and how to time a multi-course tasting menu so you actually relax instead of watching the kitchen. Most honeymoons book us for 1-3 dinners across their stay — a welcome dinner, a milestone dinner mid-trip, and a farewell dinner.",
    sections: [
      { heading: 'Common honeymoon dinner formats', bullets: [
        'Welcome night — relaxed, generous, comforting after the flight. Family-style sharing or simple 3-course plated.',
        'Milestone night — full 5-course tasting menu with sommelier-paired wines, candle setup, the big romantic moment of the trip.',
        'Farewell dinner — sentimental, often outdoors with a sunset view. Lighter menu, focused on the moment.',
        'Beach picnic lunch — chef sets up on the beach (Jimbaran, Lovina, Sanur) with chilled wine, platter food, lounge cushions.',
      ]},
      { heading: 'What\'s included for honeymoon bookings', bullets: [
        'Custom multi-course menu — your favorite cuisines, food memories, and dietary needs',
        'Candle + flower villa setup before you arrive at the table',
        'Sommelier wine pairing (optional add-on, recommended for milestone nights)',
        'Playlist coordination (your wedding songs, anniversary tracks, your specific vibe)',
        'Chef stays through service then quietly cleans up — you don\'t deal with dishes',
      ]},
      { heading: 'Pricing for honeymoon dinners', body: 'From Rp 4.5M for 2 guests all-in (3-course plated dinner with chef + ingredients + cleanup). Upgrade to a 5-course tasting menu with sommelier and full setup for Rp 6M-8M. Multi-night honeymoon packages (3+ dinners across the trip) get a 10-15% repeat-guest discount.' },
      { heading: 'Best honeymoon villa areas in Bali', body: 'Ubud (jungle and rice-field villas), Canggu (beach-adjacent with rice-field decks), Uluwatu (cliff villas with infinity pools), Seminyak (rooftop and pool villas with sunset views), Nusa Dua (resort villas with beach access). We work in all of them — most weeks we cook in 4-5 different villas across Bali.' },
    ],
    ctaSource: 'experience',
    ctaPresetOpts: { message: "Hi myCHEF — booking a private chef for our Bali honeymoon. Dates: [start]-[end], staying in [area + villa name if known]. Looking at [N] dinners across the trip." },
    ctaLabel: 'WhatsApp about a honeymoon dinner',
    secondaryCta: { label: 'See sample menus', href: '/menus' },
    structuredData: [
      ...baseSchema('honeymoon-chef', 'Honeymoon Private Chef in Bali — Villa Dining for Two | myCHEF', 'Hire a private chef for your Bali honeymoon.', 'Honeymoon Chef'),
      {
        '@context': 'https://schema.org',
        '@type': 'Service',
        '@id': 'https://mychef.id/honeymoon-chef#service',
        name: 'Honeymoon Private Chef in Bali',
        serviceType: 'Romantic private chef dinner for honeymoon couples',
        provider: { '@id': 'https://mychef.id/#organization' },
        areaServed: { '@type': 'AdministrativeArea', name: 'Bali, Indonesia' },
        offers: { '@type': 'Offer', priceCurrency: 'IDR', price: '4500000', description: 'From Rp 4.5M for 2 guests all-in (3-course plated)' },
      },
    ],
  },

  'menus/modern-european': {
    slug: 'menus/modern-european',
    canonical: 'https://mychef.id/menus/modern-european',
    title: 'Modern European Private Chef Menu in Bali — Sample Menus | myCHEF',
    description: 'Sample modern European menus from myCHEF private chefs in Bali. French, Italian, Nordic-inspired tasting menus. Plated multi-course fine dining. From Rp 5.8M for 6 guests.',
    keywords: 'modern european chef bali, french chef bali, italian chef bali, nordic chef bali, fine dining chef bali, tasting menu chef bali',
    h1: 'Modern European Private Chef Menu — Bali',
    lead: 'Plated multi-course tasting menus in the style of contemporary European fine dining — French technique, Italian precision, Nordic restraint. Our European-trained chefs reframe seasonal Bali ingredients through the lens of restaurants like Noma, Septime, and Osteria Francescana.',
    sections: [
      { heading: 'Sample Modern European Tasting Menu — 6 Courses', body: 'Rp 7.2M for 6 guests, all-in (chef + ingredients).', bullets: [
        'Snacks — beetroot meringue with goat curd; smoked mackerel tartlet; truffle gougère',
        'Cold — heirloom tomato consommé, basil oil, mascarpone',
        'Pasta — hand-rolled cavatelli, Bali mushroom ragu, brown butter, Parmesan crust',
        'Fish — wood-fired sea bass, beurre blanc, smoked salt, charred leek',
        'Meat — slow-cooked lamb shoulder, demi-glace jus, parsnip purée, pickled shallot',
        'Dessert — chocolate fondant with house-made vanilla gelato + olive oil drizzle',
      ]},
      { heading: 'Sample Italian Family-Style Sharing — 4 Courses', body: 'Rp 5.8M for 6-8 guests, all-in.', bullets: [
        'Antipasti — bresaola, burrata, charred bread, olive oil tasting, marinated olives, grissini',
        'Primi — hand-rolled tagliatelle al ragù di carne (4-hour beef ragu, brown butter, Parmesan)',
        'Secondi (sharing) — slow-cooked porchetta, balsamic-glazed onions, rosemary potatoes, Tuscan beans',
        'Dolci — tiramisu prepared tableside, espresso, soft amaretti',
      ]},
      { heading: 'When modern European wins for your villa dinner', body: 'Best for: milestone dinners (anniversary, proposal, honeymoon), corporate fine-dining offsites, guests who genuinely care about cuisine and want a "tasting menu in a restaurant" experience without leaving the villa. The chef pace is slower — courses arrive over 2.5-3 hours — so this format suits intimate dinners of 4-10 guests, not large group catering.' },
    ],
    ctaSource: 'experience',
    ctaPresetOpts: { message: "Hi myCHEF — interested in a modern European tasting menu for our villa dinner in Bali. Date: [date], [N] guests, area: [area]." },
    ctaLabel: 'WhatsApp for a modern European menu',
    structuredData: [
      ...baseSchema('menus/modern-european', 'Modern European Private Chef Menu in Bali — Sample Menus | myCHEF', 'Sample modern European menus from myCHEF private chefs in Bali.', 'Modern European'),
      {
        '@context': 'https://schema.org',
        '@type': 'Menu',
        '@id': 'https://mychef.id/menus/modern-european#menu',
        name: 'Modern European Sample Menu',
        hasMenuSection: [
          { '@type': 'MenuSection', name: '6-Course Modern European Tasting — Rp 7.2M for 6 guests', hasMenuItem: [
            { '@type': 'MenuItem', name: 'Snacks', description: 'Beetroot meringue with goat curd; smoked mackerel tartlet; truffle gougère' },
            { '@type': 'MenuItem', name: 'Cold', description: 'Heirloom tomato consommé, basil oil, mascarpone' },
            { '@type': 'MenuItem', name: 'Pasta', description: 'Hand-rolled cavatelli, Bali mushroom ragu, brown butter, Parmesan crust' },
            { '@type': 'MenuItem', name: 'Fish', description: 'Wood-fired sea bass, beurre blanc, smoked salt, charred leek' },
            { '@type': 'MenuItem', name: 'Meat', description: 'Slow-cooked lamb shoulder, demi-glace jus, parsnip purée, pickled shallot' },
            { '@type': 'MenuItem', name: 'Dessert', description: 'Chocolate fondant with house-made vanilla gelato' },
          ]},
        ],
      },
    ],
  },

  'guide/bali-cuisine-glossary': {
    slug: 'guide/bali-cuisine-glossary',
    canonical: 'https://mychef.id/guide/bali-cuisine-glossary',
    title: 'Bali & Indonesian Cuisine Glossary — Dishes, Techniques, Spices | myCHEF',
    description: 'Complete glossary of Balinese and Indonesian cooking — bebek betutu, base genep, sambal matah, lawar, rijsttafel, sayur urap, klepon. From a private chef who cooks them daily.',
    keywords: 'balinese cuisine glossary, indonesian food terms, bebek betutu meaning, base genep, sambal matah, rijsttafel, lawar, balinese spices, indonesian cooking guide',
    h1: 'Bali & Indonesian Cuisine — A Working Glossary',
    lead: "If you're planning a Balinese dinner with myCHEF, this glossary covers every term you'll see on a sample menu — what each dish is, how it's made, and what makes it special. Written by a chef who cooks these dishes weekly across Bali villas.",
    sections: [
      { heading: 'Spice pastes and sauces', bullets: [
        'Base genep — the foundational Balinese spice paste, made fresh: galangal, turmeric, ginger, garlic, shallot, candlenut, chilli, coriander seed, white pepper, cumin, cloves, nutmeg. Slow-fried in coconut oil. Goes into nearly every traditional Balinese main.',
        'Sambal matah — raw shallot + lemongrass + chilli + lime + coconut oil sambal. Cool, sharp, fragrant. Best with grilled fish or as a side to anything heavy.',
        'Sambal terasi — cooked sambal with shrimp paste, tomato, chilli. Deep umami; the everyday Indonesian table sambal.',
        'Sambal hijau — green chilli sambal with shallot, lime, salt. Lighter than terasi, great with chicken.',
        'Bumbu kuning — yellow spice paste (turmeric-forward). Used for yellow rice, gulai, opor.',
        'Bumbu rendang — dry spice mix for slow-cooked beef rendang (West Sumatran origin, eaten everywhere in Indonesia).',
      ]},
      { heading: 'Iconic dishes', bullets: [
        'Bebek betutu — duck rubbed with base genep, wrapped in banana leaf, slow-roasted for 6-8 hours. The most special-occasion Balinese dish.',
        'Babi guling — slow-roasted whole pig with base genep stuffed in the cavity. Festival food. Skin must shatter.',
        'Lawar — minced vegetable + grated coconut + spice paste salad. Often with finely chopped meat. Eaten with rice.',
        'Sayur urap — steamed vegetables tossed with toasted grated coconut + base genep. The everyday Balinese vegetable side.',
        'Ayam pelalah — shredded chicken in chilli + tomato sauce. Spicy, ubiquitous.',
        'Satay lilit — minced fish or pork wrapped around lemongrass skewers, grilled over charcoal. Balinese take on satay.',
        'Ikan bakar — whole grilled fish, basted with sambal during cooking. Best at beachfront warungs.',
        'Bebek goreng — crispy fried duck. Northern Bali specialty.',
      ]},
      { heading: 'Sharing meals + courses', bullets: [
        'Rijsttafel — Dutch-Indonesian colonial-era "rice table": 12-25 small dishes served at once around a central rice serving. Now the gold standard for sharing-feast Indonesian dining.',
        'Nasi campur — "mixed rice": single plate of rice with 4-6 toppings (lawar, ayam, sayur, sambal, krupuk). The default Indonesian meal.',
        'Nasi kuning — yellow turmeric rice. Festival rice. Cone-shaped at ceremonies (tumpeng).',
        'Gado-gado — vegetable salad with peanut sauce. Indonesian; not specifically Balinese but eaten everywhere.',
        'Tumpeng — yellow rice molded into a cone, surrounded by side dishes. Served at celebrations.',
      ]},
      { heading: 'Sweets', bullets: [
        'Klepon — green pandan rice flour balls filled with palm sugar, rolled in coconut. Bursts in your mouth.',
        'Dadar gulung — green pandan crepes filled with coconut + palm sugar.',
        'Bubur injin — black rice porridge with coconut milk + palm sugar. Often eaten for breakfast.',
        'Kolak — sweet coconut milk soup with banana, sweet potato, palm sugar.',
        'Es campur — shaved ice with sweet beans, coconut, jelly, palm sugar. Bali summer dessert.',
      ]},
      { heading: 'Cooking techniques + ingredients', bullets: [
        'Banana leaf wrapping — protects food during slow roasting, infuses faint vegetal aroma. Used for betutu, satay lilit, pepes (steamed/grilled fish parcels).',
        'Coconut oil — the everyday cooking oil in Bali (palm oil is rare in traditional cooking). Adds aroma to sautés.',
        'Palm sugar (gula merah) — the sweetener of choice. Caramel-like, slightly smoky. Used everywhere from sambal to dessert.',
        'Kecap manis — sweet soy sauce. Indonesian invention. The base of nasi goreng and many marinades.',
        'Krupuk — fried rice or shrimp crackers. Always on the table.',
        'Tempeh — fermented soy bean cake. Indonesian, NOT Vegan-Western. Slice, marinate in kecap, fry; or stew.',
      ]},
    ],
    ctaSource: 'experience',
    ctaPresetOpts: { message: "Hi myCHEF — interested in a Balinese tasting menu in our villa. Have read your cuisine glossary; want to discuss specific dishes." },
    ctaLabel: 'WhatsApp about a Balinese menu',
    secondaryCta: { label: 'Browse Balinese sample menus', href: '/menus/balinese' },
    structuredData: [
      ...baseSchema('guide/bali-cuisine-glossary', 'Bali & Indonesian Cuisine Glossary — Dishes, Techniques, Spices | myCHEF', 'Complete glossary of Balinese and Indonesian cooking.', 'Bali Cuisine Glossary'),
      {
        '@context': 'https://schema.org',
        '@type': 'Article',
        '@id': 'https://mychef.id/guide/bali-cuisine-glossary#article',
        headline: 'Bali & Indonesian Cuisine — A Working Glossary',
        description: 'Complete glossary of Balinese and Indonesian cooking — dishes, techniques, spices.',
        author: { '@id': 'https://mychef.id/#organization' },
        publisher: { '@id': 'https://mychef.id/#organization' },
        datePublished: '2026-05-12',
        dateModified: '2026-05-12',
        inLanguage: 'en',
        about: { '@type': 'Thing', name: 'Balinese cuisine' },
      },
    ],
  },

  'guide/private-chef-bali': {
    slug: 'guide/private-chef-bali',
    canonical: 'https://mychef.id/guide/private-chef-bali',
    title: 'Private Chef in Bali — Complete 2026 Booking Guide | myCHEF',
    description: 'Complete guide to hiring a private chef in Bali: pricing, booking timeline, area selection, cuisine choice, dietary restrictions, what to expect on the night. From a 13-year operator.',
    keywords: 'private chef bali guide, how to hire private chef bali, private chef bali cost, private chef bali booking, what to expect private chef bali',
    h1: 'How to Hire a Private Chef in Bali — Complete 2026 Guide',
    lead: "myCHEF Indonesia has booked thousands of private chef nights in Bali villas since 2012. This is the practical guide we wish more first-time bookers had — pricing, timeline, area selection, cuisine fit, dietary handling, and what actually happens on the night.",
    sections: [
      { heading: 'Step 1 — When to book', body: "For premium Bali areas (Canggu, Seminyak, Ubud, Uluwatu) we recommend booking 5-10 days in advance. Top chefs book up especially for weekends in peak season (June-August, December). Same-day bookings are usually possible in Canggu and Seminyak via WhatsApp; rare in Ubud or far-from-Denpasar areas like Lovina." },
      { heading: 'Step 2 — Choose the right cuisine for the occasion', bullets: [
        'Welcome night for a group: family-style sharing menu (Mediterranean or Balinese rijsttafel)',
        'Romantic milestone: 5-course tasting (modern European or Mediterranean) with sommelier wine pairing',
        'Mixed-age family with kids: 3-course plated dinner with a kid-friendly version of each course',
        'Vegan retreat or wellness focus: full plant-based tasting menu',
        'Cultural immersion + special occasion: traditional Balinese rijsttafel with sambal trio',
        'Corporate offsite: pan-Asian fusion or modern European with sommelier; plated to keep conversation flowing',
      ]},
      { heading: 'Step 3 — Match the area to the experience', body: "Where you stay shapes what kind of dinner works. Canggu villas have outdoor kitchens and beach-walk distance — best for casual Mediterranean dinners and grilled mains. Seminyak villas tend to have formal indoor dining + sunset terraces — best for plated multi-course menus. Ubud villas face rice fields with open-air decks — best for Balinese rijsttafel or vegan tasting menus. Uluwatu cliff villas have infinity pool views — best for fine-dining tasting menus. Nusa Dua resort villas have beach access — best for fresh seafood." },
      { heading: 'Step 4 — Pricing and what\'s actually included', body: 'Chef fee: from Rp 800,000 per hour (3-hour minimum). Most villa dinners run 3-5 hours total chef time. Ingredients are billed at market cost — typically Rp 250,000-500,000 per guest for premium Mediterranean / European dinners; Rp 150,000-300,000 per guest for Balinese / Asian. Add-on staff: waiter Rp 300k/hr, bartender Rp 400k/hr, sommelier Rp 500k/hr. Equipment, plating, and cleanup are included in the chef rate. Total for a 4-course dinner for 6 guests typically lands at Rp 3.5M-5M all-in.' },
      { heading: 'Step 5 — Dietary restrictions and special needs', body: "Tell us during booking, not on the night. Common: vegan, vegetarian, gluten-free, dairy-free, halal, kosher, low-carb, paleo, allergen-restricted (nut, shellfish, etc.). For mixed groups (e.g. one vegan among 6 guests), we build the same menu with a parallel vegan plate for that guest — same plating quality, same course timing. For halal we source from MUI-certified suppliers — see /menus/halal." },
      { heading: 'Step 6 — What happens on the night', steps: [
        { title: 'Chef arrives', description: '2-3 hours before service. Greets host, sets up kitchen workflow, unpacks ingredients.' },
        { title: 'Cooking', description: 'Most prep happens in your kitchen (you can watch if you want). Some prep at base.' },
        { title: 'Service', description: 'Plated courses delivered to your table on the timing you set. Chef explains each dish briefly if you want; silent if you don\'t.' },
        { title: 'Cleanup', description: 'Chef cleans the kitchen, packs out, leaves with the kitchen the way they found it. You don\'t deal with dishes.' },
      ]},
      { heading: 'Step 7 — How to book myCHEF specifically', body: 'WhatsApp +62 822-3756-5997 with: date, area, guest count, any cuisine preferences, any dietary restrictions, the occasion (welcome dinner / proposal / birthday / etc.), your villa name if known. We respond in under 10 minutes during operating hours (09:00-22:00 WIB). Most bookings are confirmed in under an hour.' },
    ],
    ctaSource: 'experience',
    ctaPresetOpts: { message: "Hi myCHEF — read your booking guide, ready to book. Date: [date], area: [area], [N] guests, occasion: [...]." },
    ctaLabel: 'WhatsApp to book a chef',
    secondaryCta: { label: 'See sample menus', href: '/menus' },
    structuredData: [
      ...baseSchema('guide/private-chef-bali', 'Private Chef in Bali — Complete 2026 Booking Guide | myCHEF', 'Complete guide to hiring a private chef in Bali.', 'Booking Guide'),
      {
        '@context': 'https://schema.org',
        '@type': 'Article',
        '@id': 'https://mychef.id/guide/private-chef-bali#article',
        headline: 'How to Hire a Private Chef in Bali — Complete 2026 Guide',
        description: 'Practical guide to hiring a private chef in Bali: pricing, booking timeline, area selection, cuisine choice, dietary restrictions.',
        author: { '@id': 'https://mychef.id/#organization' },
        publisher: { '@id': 'https://mychef.id/#organization' },
        datePublished: '2026-05-12',
        dateModified: '2026-05-12',
        inLanguage: 'en',
      },
    ],
  },

  'echo-beach-private-chef': {
    slug: 'echo-beach-private-chef',
    canonical: 'https://mychef.id/echo-beach-private-chef',
    title: 'Private Chef in Echo Beach, Canggu — Surf-Side Villa Dining | myCHEF',
    description: 'Background-checked private chef for Echo Beach villas in Canggu. Sunset terraces, surf-camp catering, beach-walk villas. Mediterranean + Asian fusion. WhatsApp booking.',
    keywords: 'private chef echo beach, echo beach villa chef, canggu echo beach chef, surf camp chef bali, echo beach catering',
    h1: 'Private Chef in Echo Beach, Canggu',
    lead: "Echo Beach is Canggu's most photogenic stretch of coast — laid-back surfer-meets-luxury-villa vibe, sunset crowds at the warungs, beach-walk villas with open-air kitchens. myCHEF cooks regularly in Echo Beach villas. Our chefs know the kitchen layouts of most luxury rentals along Jalan Pantai Batu Mejan.",
    sections: [
      { heading: 'Why Echo Beach villas suit private chef dining', bullets: [
        'Outdoor villa kitchens common — fits Mediterranean grill menus, wood-fired fish, satay over charcoal',
        'Many villas have direct beach access — beachside cocktail setup before dinner is straightforward',
        'Sunset is ~18:30 — typical 7pm dinner timing means cocktails on the deck during golden hour',
        'Casual lifestyle area — guests prefer family-style sharing menus over rigid plated tasting menus',
      ]},
      { heading: 'Common Echo Beach booking types', bullets: [
        'Surf-trip group dinners (4-12 guests) — Mediterranean grills, family-style sharing',
        'Couple welcome / farewell dinners — modern European or Asian fusion',
        'Sunset proposal dinners on the villa terrace — see /proposal-dinner',
        'Wellness retreat catering at Echo Beach yoga retreats — vegan + plant-based focus',
        'Birthday celebrations with photographer + cake — see /services/birthday-celebrations',
      ]},
      { heading: 'Sample Echo Beach 3-course Mediterranean dinner', bullets: [
        'Starter — Burrata, heirloom tomato, basil oil, sourdough',
        'Main — Wood-fired snapper (caught at Jimbaran morning market), salsa verde, charred lemon, smoked paprika potatoes',
        'Dessert — Coconut panna cotta, Tegallalang strawberries, basil sugar',
      ]},
      { heading: 'Pricing in Echo Beach', body: 'Same as Canggu — from Rp 800,000 per hour, 3-hour minimum + ingredients at cost. No additional travel fee for Echo Beach villas. WhatsApp +62 822-3756-5997.' },
    ],
    ctaSource: 'cityHero',
    ctaPresetOpts: { city: 'Echo Beach, Canggu' },
    ctaLabel: 'WhatsApp for an Echo Beach chef',
    secondaryCta: { label: 'See Canggu page', href: '/canggu' },
    structuredData: [
      ...baseSchema('echo-beach-private-chef', 'Private Chef in Echo Beach, Canggu — Surf-Side Villa Dining | myCHEF', 'Background-checked private chef for Echo Beach villas in Canggu.', 'Echo Beach'),
      {
        '@context': 'https://schema.org',
        '@type': 'Service',
        '@id': 'https://mychef.id/echo-beach-private-chef#service',
        name: 'Private Chef in Echo Beach, Canggu, Bali',
        serviceType: 'Private chef and in-villa dining in Echo Beach',
        provider: { '@id': 'https://mychef.id/#organization' },
        areaServed: { '@type': 'Place', name: 'Echo Beach, Canggu', containedInPlace: { '@type': 'City', name: 'Canggu' } },
      },
    ],
  },

  'batu-bolong-private-chef': {
    slug: 'batu-bolong-private-chef',
    canonical: 'https://mychef.id/batu-bolong-private-chef',
    title: 'Private Chef in Batu Bolong, Canggu — Creative Hub Villa Dining | myCHEF',
    description: 'Background-checked private chef for Batu Bolong villas in Canggu. Creative neighborhood, plant-based focus, surf + work crowd. Mediterranean + vegan menus. WhatsApp.',
    keywords: 'private chef batu bolong, batu bolong canggu villa chef, batu bolong vegan chef, batu bolong dinner',
    h1: 'Private Chef in Batu Bolong, Canggu',
    lead: 'Batu Bolong is Canggu\'s creative hub — laptop-cafés meets surf hostels meets luxury rice-field villas. The crowd skews younger, more wellness-focused, more plant-based curious. myCHEF\'s Batu Bolong bookings are often vegan-leaning Mediterranean menus or modern Indonesian fusion for digital-nomad birthday dinners.',
    sections: [
      { heading: 'Why Batu Bolong is a different vibe than Echo Beach or Berawa', body: 'Batu Bolong is more density-mixed: modern luxury villas backing onto rice fields, but also surf hostels and warungs within walking distance. The food scene is dominated by plant-based cafés (Crate, Peloton Supershop, Milu) and modern Indonesian (Crate Café). Private chef bookings here lean toward conscious-eating menus — vegan, anti-inflammatory, organic-forward.' },
      { heading: 'Common Batu Bolong menus', bullets: [
        'Vegan Mediterranean sharing — see /menus/vegan',
        'Plant-based 5-course tasting menu (Rp 5.4M for 6)',
        'Modern Indonesian — gado-gado refined, sambal trio, ikan bakar with locally-grown vegetables',
        'Anti-inflammatory wellness menus — no refined sugar, no dairy, organic only',
      ]},
      { heading: 'Best Batu Bolong dinner formats', bullets: [
        'Digital nomad / community group dinners (8-15 guests, family-style)',
        'Vegan birthday + anniversary dinners',
        'Yoga teacher training catering at Batu Bolong studios',
        'Surf-trip wellness dinners — recovery-focused menus',
      ]},
      { heading: 'Pricing in Batu Bolong', body: 'Same as Canggu — from Rp 800,000 per hour, 3-hour minimum + ingredients at cost. No travel fee. WhatsApp +62 822-3756-5997.' },
    ],
    ctaSource: 'cityHero',
    ctaPresetOpts: { city: 'Batu Bolong, Canggu' },
    ctaLabel: 'WhatsApp for a Batu Bolong chef',
    secondaryCta: { label: 'See Canggu page', href: '/canggu' },
    structuredData: [
      ...baseSchema('batu-bolong-private-chef', 'Private Chef in Batu Bolong, Canggu — Creative Hub Villa Dining | myCHEF', 'Background-checked private chef for Batu Bolong villas in Canggu.', 'Batu Bolong'),
      {
        '@context': 'https://schema.org',
        '@type': 'Service',
        '@id': 'https://mychef.id/batu-bolong-private-chef#service',
        name: 'Private Chef in Batu Bolong, Canggu, Bali',
        serviceType: 'Private chef and in-villa dining in Batu Bolong',
        provider: { '@id': 'https://mychef.id/#organization' },
      },
    ],
  },

  'bingin-private-chef': {
    slug: 'bingin-private-chef',
    canonical: 'https://mychef.id/bingin-private-chef',
    title: 'Private Chef in Bingin, Uluwatu — Cliff-Top Villa Dining | myCHEF',
    description: 'Background-checked private chef for Bingin Beach villas in Uluwatu. Cliff-top sunset villas, surf-camp catering, fine-dining tasting menus. WhatsApp booking.',
    keywords: 'private chef bingin, bingin uluwatu chef, bingin beach villa chef, bingin sunset dinner',
    h1: 'Private Chef in Bingin, Uluwatu',
    lead: 'Bingin sits on the Bukit peninsula\'s western cliffs — long sandy beach below, surfer enclave above, world-class sunsets every night. Bingin villas are mostly cliff-top with infinity pools facing the Indian Ocean. myCHEF cooks Mediterranean and modern European tasting menus here for honeymoons, surf-trip group dinners, and milestone events.',
    sections: [
      { heading: 'Why Bingin villas suit fine-dining tasting menus', bullets: [
        'Cliff-top setting demands an experience that matches the view — multi-course plated menus over fast-casual',
        'Sunset (~18:30) lines up with first course timing — start with cocktails on the deck',
        'Indoor + outdoor villa kitchens give flexibility for Mediterranean grills + plated entrées',
        'Quiet area — chef doesn\'t compete with beach-club music; full restaurant-grade experience possible',
      ]},
      { heading: 'Common Bingin booking types', bullets: [
        'Honeymoon couple dinners — see /honeymoon-chef',
        'Proposal dinners with sommelier — see /proposal-dinner',
        'Small wedding ceremonies (8-30 guests)',
        'Surf-trip group dinners (10-20 guests)',
        'Multi-day private chef placements for villa renters staying 5+ nights',
      ]},
      { heading: 'Pricing in Bingin', body: 'Same as Uluwatu base rate — from Rp 800,000 per hour, 3-hour minimum + ingredients at cost. Small Bukit travel surcharge may apply for villas in remote cliff locations. WhatsApp +62 822-3756-5997.' },
    ],
    ctaSource: 'cityHero',
    ctaPresetOpts: { city: 'Bingin, Uluwatu' },
    ctaLabel: 'WhatsApp for a Bingin chef',
    secondaryCta: { label: 'See Uluwatu page', href: '/uluwatu' },
    structuredData: [
      ...baseSchema('bingin-private-chef', 'Private Chef in Bingin, Uluwatu — Cliff-Top Villa Dining | myCHEF', 'Background-checked private chef for Bingin Beach villas in Uluwatu.', 'Bingin'),
      {
        '@context': 'https://schema.org',
        '@type': 'Service',
        '@id': 'https://mychef.id/bingin-private-chef#service',
        name: 'Private Chef in Bingin, Uluwatu, Bali',
        serviceType: 'Private chef and in-villa dining in Bingin',
        provider: { '@id': 'https://mychef.id/#organization' },
      },
    ],
  },

  'pricing': {
    slug: 'pricing',
    canonical: 'https://mychef.id/pricing',
    title: 'Private Chef Pricing in Bali — Rp 800k/hr, 3-Hour Min | myCHEF',
    description: 'Transparent private chef pricing in Bali. Chef fee from Rp 800k/hr (3-hr min) + ingredients at cost. Add-on staff: waiter Rp 300k, bartender Rp 400k, sommelier Rp 500k.',
    keywords: 'private chef cost bali, private chef price bali, how much private chef bali, mychef pricing, bali chef hourly rate',
    h1: 'Private Chef Pricing in Bali',
    lead: "Transparent pricing — no hidden fees, no minimum order trays, no service-charge markup. Chef fee is per hour with a 3-hour minimum. Ingredients are billed at cost (the chef shops at local markets and provides receipts). Add-on staff are clearly priced. Below is everything you'll see on a quote.",
    sections: [
      { heading: 'Chef fee', body: 'Rp 800,000 per hour. 3-hour minimum (covers prep, cooking, service, cleanup). Most villa dinners use 3-5 hours of chef time.' },
      { heading: "What's included in the chef rate", bullets: [
        'Cooking labor — all menu prep + on-site cooking',
        'Plating and presentation',
        'Service through the meal',
        'Kitchen cleanup after service (kitchen returned to villa state)',
        'Standard chef equipment (knives, tools)',
        'Menu consultation before the event',
      ]},
      { heading: 'Ingredients', body: 'Billed at cost. Typical range: Rp 250,000–500,000 per guest for premium Mediterranean / European menus; Rp 150,000–300,000 per guest for Balinese / Asian fusion. Chef provides market receipts. No markup.' },
      { heading: 'Add-on staff (optional)', bullets: [
        'Waiter — Rp 300,000 per hour. Recommended for plated tasting menus 6+ guests.',
        'Bartender — Rp 400,000 per hour. Recommended for cocktail-forward events.',
        'Sommelier with wine pairing — Rp 500,000 per hour. For multi-course dinners.',
      ]},
      { heading: 'Specialty event pricing (all-in, ingredients included)', bullets: [
        'Three-course Mediterranean villa dinner — from Rp 4.2M for 6 guests',
        'Five-course Mediterranean tasting menu — from Rp 7.8M for 6 guests',
        'Family-style Mediterranean sharing feast — from Rp 5.5M for 8-10 guests',
        'Traditional Balinese rijsttafel — from Rp 4.8M for 6-8 guests',
        'Modern Balinese tasting menu — from Rp 6.8M for 6 guests',
        'Vegan plant-based tasting menu — from Rp 5.4M for 6 guests',
        'Asian fusion tasting menu — from Rp 5.8M for 6 guests',
        'Halal-certified multi-course menu — from Rp 5.4M for 6 guests',
        'Modern European 6-course tasting menu — from Rp 7.2M for 6 guests',
        'Proposal dinner with sommelier + setup — from Rp 6M for 2 guests',
        'Honeymoon villa dinner (3-course) — from Rp 4.5M for 2 guests',
      ]},
      { heading: 'Recurring + long-term arrangements', bullets: [
        'Weekly meal-prep contract (1-3 sessions/week) — from Rp 2.5M per session',
        'Multi-day retreat catering (3+ days, 8-50 guests) — from Rp 1.5M per chef per day + ingredients',
        'Yoga teacher training catering (10-30 days, 3 meals/day for 20 guests) — Rp 350k-550k per guest per day all-in',
        'Full-time household chef placement — quoted per arrangement',
      ]},
      { heading: 'Travel surcharges', body: 'No travel fee for Canggu, Seminyak, Ubud, Uluwatu, Nusa Dua, Sanur, Jimbaran, Kuta, Denpasar. Small surcharge for Lovina, Amed, Candidasa, Padang Bai (covering chef transport time).' },
      { heading: 'Payment + cancellation', body: '50% deposit on booking confirmation, 50% balance due 24 hours before service. Bank transfer (BCA, Mandiri), credit card, or cash in IDR. Cancellation: full refund 7+ days before, 50% refund 3-7 days before, no refund <72h before (chef has already been booked).' },
      { heading: 'Get an exact quote in under an hour', body: 'Pricing depends on guest count, menu complexity, area, and dietary needs. WhatsApp +62 822-3756-5997 with the details and we send a written quote within an hour during operating hours.' },
    ],
    ctaSource: 'pricing',
    ctaPresetOpts: { message: "Hi myCHEF — need a custom price quote. Date: [date], [N] guests, area: [area], cuisine: [Mediterranean/Balinese/etc], any dietary restrictions: [...]." },
    ctaLabel: 'WhatsApp for a custom quote',
    secondaryCta: { label: 'Pricing calculator', href: '/calculator' },
    structuredData: [
      ...baseSchema('pricing', 'Private Chef Pricing in Bali — Rp 800k/hr, 3-Hour Min | myCHEF', 'Transparent private chef pricing in Bali.', 'Pricing'),
      {
        '@context': 'https://schema.org',
        '@type': 'PriceSpecification',
        '@id': 'https://mychef.id/pricing#chef-rate',
        price: 800000,
        priceCurrency: 'IDR',
        unitCode: 'HUR',
        unitText: 'per hour',
        minPrice: 2400000,
        description: 'Chef fee — from Rp 800,000/hour, 3-hour minimum. Ingredients at cost.',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'Service',
        '@id': 'https://mychef.id/pricing#service',
        name: 'Private Chef Pricing — Bali',
        provider: { '@id': 'https://mychef.id/#organization' },
        areaServed: { '@type': 'AdministrativeArea', name: 'Bali, Indonesia' },
        offers: [
          { '@type': 'Offer', priceCurrency: 'IDR', price: '800000', description: 'From Rp 800,000/hour, 3-hour minimum (chef fee)' },
          { '@type': 'Offer', priceCurrency: 'IDR', price: '4200000', description: 'Three-course Mediterranean dinner for 6 guests, all-in' },
          { '@type': 'Offer', priceCurrency: 'IDR', price: '6000000', description: 'Proposal dinner for 2 guests, all-in (5-course + sommelier)' },
          { '@type': 'Offer', priceCurrency: 'IDR', price: '2500000', description: 'Weekly meal-prep session (per session)' },
        ],
      },
    ],
  },

  'private-chef-cost-bali': {
    slug: 'private-chef-cost-bali',
    canonical: 'https://mychef.id/private-chef-cost-bali',
    title: 'How Much Does a Private Chef Cost in Bali? — 2026 Guide | myCHEF',
    description: "Complete cost breakdown for hiring a private chef in Bali. Per-hour rates, per-guest costs, all-in pricing for villa dinners. From Rp 800k/hr. Get a quote in under an hour.",
    keywords: 'private chef cost bali, how much private chef bali, private chef price bali, bali chef rate, mychef cost',
    h1: 'How Much Does a Private Chef Cost in Bali?',
    lead: "Direct answer: from Rp 800,000 per hour with a 3-hour minimum, plus ingredients at cost. A typical 4-course dinner for 6 guests works out to Rp 3.5M-4.5M total all-in (chef fee + ingredients + cleanup). This guide explains where every rupiah goes so you know exactly what to expect on a quote.",
    sections: [
      { heading: 'Per-hour chef fee', body: 'Rp 800,000 per hour. 3-hour minimum. Most villa dinners use 3-5 hours of chef time (2 hours prep + 1.5 hours service + 30 min cleanup). The hourly rate includes cooking, plating, presentation, and kitchen cleanup. Equipment, knives, and standard chef tools are included.' },
      { heading: 'Per-guest ingredient cost', bullets: [
        'Mediterranean / modern European premium menus: Rp 250,000–500,000 per guest',
        'Asian fusion / Balinese / Indonesian menus: Rp 150,000–300,000 per guest',
        'Vegan / plant-based menus: Rp 200,000–400,000 per guest',
        'Halal-certified menus: Rp 250,000–450,000 per guest (sourcing from MUI-certified suppliers)',
        'Premium proteins (wagyu, foie gras, truffle, langoustine): add Rp 200,000-800,000 per guest',
      ]},
      { heading: 'Real example: 4-course dinner for 6 guests in Canggu', body: 'Chef fee: Rp 800k × 4 hours = Rp 3.2M. Ingredients: Rp 350k × 6 guests = Rp 2.1M. Total all-in: Rp 5.3M (~$340 USD at current exchange). Per-guest cost: Rp 880k (~$57 USD per guest). For comparison, a similar 4-course tasting menu at a top Seminyak restaurant runs Rp 1.5M-2M per guest including transport.' },
      { heading: 'Add-on staff costs', bullets: [
        'Waiter (recommended for plated multi-course dinners 6+ guests): Rp 300,000/hour, 3-hr min',
        'Bartender (cocktail bar service for parties): Rp 400,000/hour, 3-hr min',
        'Sommelier (wine pairing for tasting menus): Rp 500,000/hour, 3-hr min',
      ]},
      { heading: 'How myCHEF cost compares to alternatives', bullets: [
        'Catering company for 6 guests: typically Rp 4.5M-7M total (most goes to service + transport markup). myCHEF for same 6 guests: Rp 3.5M-4.5M, fresher food.',
        'Restaurant tasting menu for 6 guests: Rp 9M-12M (Rp 1.5M-2M per guest at top restaurants). Plus transport. myCHEF in your villa: <half the cost, no transport.',
        'Hotel restaurant in-room dining: usually 30-50% premium over restaurant menu price + service charge. myCHEF: no markup, more flexibility.',
      ]},
      { heading: 'When private chef costs MORE', body: "For very large groups (50+ guests), traditional catering wins on per-guest economics because of kitchen scale. For under 30 guests, private chef is almost always better value because there's no minimum-order or service-charge markup." },
      { heading: 'Get a written quote in under an hour', body: 'WhatsApp +62 822-3756-5997 with: date, area, guest count, cuisine, dietary restrictions, occasion. We respond in under 10 minutes during operating hours (09:00-22:00 WIB) and send a full written quote with chef profile + sample menu within an hour.' },
    ],
    ctaSource: 'pricing',
    ctaPresetOpts: { message: "Hi myCHEF — need a price quote. Date: [date], [N] guests, area: [area], cuisine preference: [...]." },
    ctaLabel: 'WhatsApp for a price quote',
    secondaryCta: { label: 'Full pricing page', href: '/pricing' },
    structuredData: [
      ...baseSchema('private-chef-cost-bali', 'How Much Does a Private Chef Cost in Bali? — 2026 Guide | myCHEF', 'Complete cost breakdown for hiring a private chef in Bali.', 'Private Chef Cost'),
      {
        '@context': 'https://schema.org',
        '@type': 'Article',
        '@id': 'https://mychef.id/private-chef-cost-bali#article',
        headline: 'How Much Does a Private Chef Cost in Bali? 2026 Guide',
        description: 'Complete cost breakdown for hiring a private chef in Bali — per-hour rates, per-guest costs, all-in pricing.',
        author: { '@id': 'https://mychef.id/#organization' },
        publisher: { '@id': 'https://mychef.id/#organization' },
        datePublished: '2026-05-12',
        dateModified: '2026-05-12',
        about: { '@type': 'Thing', name: 'Private chef pricing in Bali' },
      },
    ],
  },

  'why-mychef': {
    slug: 'why-mychef',
    canonical: 'https://mychef.id/why-mychef',
    title: 'Why myCHEF — Private Chef vs Catering vs Restaurant in Bali | myCHEF',
    description: 'When does a private chef beat catering or restaurant dining in Bali? Side-by-side comparison: cost, freshness, customisation, service, logistics. From a 13-year operator.',
    keywords: 'why private chef bali, private chef vs catering, private chef vs restaurant bali, mychef vs catering, best private chef bali',
    h1: 'Why myCHEF — Private Chef vs Catering vs Restaurant',
    lead: "If you're choosing between hiring a private chef, ordering catering, or just going to a restaurant, this page lays out exactly when each option wins. From a 13-year operator who has watched the alternatives evolve in Bali.",
    sections: [
      { heading: 'Private chef (myCHEF) — when it wins', bullets: [
        'You want fresh-cooked food, not pre-made trays',
        'Group of 4-30 guests (the sweet spot economics)',
        'Special occasion: anniversary, proposal, milestone, honeymoon',
        'Mixed dietary needs (vegan + carnivore at same table — easy)',
        'You want the experience: chef explains dishes, takes wine cues, adapts in real time',
        'You want to relax in your villa rather than book transport + reservations',
      ]},
      { heading: 'Traditional catering — when it wins', bullets: [
        'Very large groups (50+ guests) where kitchen scale matters',
        'Buffet-style events where staying-warm food works fine',
        'Industrial-volume corporate events (lunch boxes for 100 attendees)',
        'When you accept pre-cooked food in trays in exchange for volume pricing',
      ]},
      { heading: 'Going to a restaurant — when it wins', bullets: [
        'You want the restaurant atmosphere (live music, view, bar scene)',
        'Trying a chef whose particular technique only works in their restaurant kitchen',
        'Solo or 2-person dining where private chef minimum makes it expensive per guest',
        "You don't have a villa kitchen — staying in a hotel room with no cooking space",
      ]},
      { heading: 'Cost side-by-side (4-course dinner for 6 guests)', bullets: [
        'myCHEF private chef: Rp 3.5M-4.5M total all-in. Cooked fresh in your villa.',
        'Bali catering company: Rp 4.5M-7M total. Pre-cooked, delivered in trays.',
        'Top Seminyak restaurant: Rp 9M-12M total + transport. Cooked at restaurant.',
        'Hotel restaurant (e.g. Ku De Ta) with in-room service: Rp 12M-15M+. Restaurant menu + 30% service markup.',
      ]},
      { heading: 'Freshness side-by-side', bullets: [
        'myCHEF: chef shops at the morning market and cooks 3 hours later. Maximum freshness.',
        'Catering: cooked at the catering kitchen 4-8 hours before arrival, transported in heating boxes.',
        'Restaurant: cooked 5-15 minutes before service. Same as private chef.',
        'In-room service: same as restaurant + transport time (10-30 min cooler).',
      ]},
      { heading: 'Customisation side-by-side', bullets: [
        'myCHEF: full custom menu before the event + real-time adjustments during (allergens, picky eaters, kid-friendly versions). 100% flexible.',
        'Catering: menu locked 24-48 hours before. Limited substitutions. Allergen handling is risky.',
        'Restaurant: order from the menu. Some special requests possible. No real customisation.',
        'In-room: same as restaurant.',
      ]},
      { heading: 'When myCHEF is NOT the right answer', body: "We're the wrong choice if: you have 100+ guests (call a catering company); you want the restaurant scene (go to the restaurant); you're solo and don't have a villa kitchen (room service or restaurant); you want the cheapest possible food (a Bali warung is unbeatable). For everything else — villa dinners, special occasions, retreats, weekly meal-prep, household chef arrangements — we're built for it." },
    ],
    ctaSource: 'experience',
    ctaPresetOpts: { message: "Hi myCHEF — comparing private chef vs catering vs restaurant for our event. Date: [date], [N] guests, area: [area]. Can you walk me through the options?" },
    ctaLabel: 'WhatsApp myCHEF',
    secondaryCta: { label: 'See pricing', href: '/pricing' },
    structuredData: [
      ...baseSchema('why-mychef', 'Why myCHEF — Private Chef vs Catering vs Restaurant in Bali | myCHEF', 'Side-by-side comparison: private chef vs catering vs restaurant in Bali.', 'Why myCHEF'),
      {
        '@context': 'https://schema.org',
        '@type': 'Article',
        '@id': 'https://mychef.id/why-mychef#article',
        headline: 'Why myCHEF — Private Chef vs Catering vs Restaurant in Bali',
        description: 'When private chef beats catering or restaurant dining in Bali. Side-by-side comparison.',
        author: { '@id': 'https://mychef.id/#organization' },
        publisher: { '@id': 'https://mychef.id/#organization' },
        datePublished: '2026-05-12',
        dateModified: '2026-05-12',
      },
    ],
  },

  'reviews': {
    slug: 'reviews',
    canonical: 'https://mychef.id/reviews',
    title: 'myCHEF Reviews — Private Chef Bali Customer Feedback | myCHEF',
    description: "Read what guests say about myCHEF's private chef service in Bali. Real reviews from villa dinners, weddings, retreats, and recurring household chef placements since 2012.",
    keywords: 'mychef reviews, private chef bali reviews, mychef testimonials, mychef customer feedback',
    h1: 'myCHEF Reviews & Customer Feedback',
    lead: "myCHEF has cooked thousands of dinners across Bali since 2012. We're consolidating all customer feedback in one place — Trustpilot, Google Business Profile, Tripadvisor, and direct testimonials. New review widgets coming soon. In the meantime, here's the structure of how we work and how we ask for feedback.",
    sections: [
      { heading: 'Where we collect reviews', bullets: [
        'Google Business Profile — primary source (drives map-pack visibility)',
        'Trustpilot — secondary source (independent third-party verification)',
        'Tripadvisor — for tourists searching alongside Bali activity reviews',
        'Direct testimonials — collected via WhatsApp follow-up after service',
      ]},
      { heading: 'How we follow up', body: '24 hours after every booking, we WhatsApp the host: "Hope last night was perfect — would you mind leaving us a quick review?" with three direct links (Google, Trustpilot, Tripadvisor). Most reviews come from this single follow-up.' },
      { heading: 'What guests typically mention', bullets: [
        'Chef arrived on time, set up smoothly',
        'Menu adapted to dietary needs (vegan + carnivore + kid-friendly all in one dinner)',
        'Plating and presentation matched a top restaurant',
        'Chef was professional but warm — explained dishes without being intrusive',
        'Kitchen was cleaner after the chef left than before',
        'Booking + WhatsApp communication was fast and clear',
      ]},
      { heading: 'Reviewing myCHEF — direct links (after your event)', body: "After your booking, we'll send the direct links via WhatsApp. If you want to leave a review now without booking yet, reach us via WhatsApp +62 822-3756-5997 and we'll send the relevant links." },
      { heading: 'Verified Trustpilot widget — coming soon', body: "We're integrating a verified Trustpilot widget that will display all reviews here in real time, with star rating + count. The widget pulls live from Trustpilot's API so reviews can't be edited or filtered. Schema-marked for Google rich-result eligibility." },
    ],
    ctaSource: 'testimonials',
    ctaLabel: 'WhatsApp to leave a review',
    secondaryCta: { label: 'See how booking works', href: '/guide/private-chef-bali' },
    structuredData: [
      ...baseSchema('reviews', 'myCHEF Reviews — Private Chef Bali Customer Feedback | myCHEF', "Read what guests say about myCHEF's private chef service in Bali.", 'Reviews'),
    ],
  },

  'sayan-private-chef': {
    slug: 'sayan-private-chef',
    canonical: 'https://mychef.id/sayan-private-chef',
    title: 'Private Chef in Sayan, Ubud — Ayung River Villa Dining | myCHEF',
    description: 'Background-checked private chef for Sayan villas in Ubud. Ayung River views, jungle villas, modern Balinese + vegan tasting menus. From Rp 800k/hr. WhatsApp.',
    keywords: 'private chef sayan ubud, sayan villa chef, ubud sayan dinner, ayung river villa chef',
    h1: 'Private Chef in Sayan, Ubud',
    lead: "Sayan is Ubud's most exclusive valley — Ayung River views, terraced jungle villas, the home of Four Seasons Sayan and Mandapa. The crowd here is high-end honeymooners, wellness travellers, and long-stay creatives. myCHEF cooks modern Balinese + vegan tasting menus in Sayan villa kitchens regularly.",
    sections: [
      { heading: 'Why Sayan villas suit fine-dining tasting menus', bullets: [
        'River-view kitchens with outdoor decks — perfect for sunset multi-course dining',
        'Premium villa kitchens (most Sayan rentals are luxury-grade) — full equipment for tasting menus',
        'Quiet location — restaurants are 15-min drive away, private chef genuinely the easier option',
        'Honeymoon and wellness audience — willing to pay for quality, food-conscious',
      ]},
      { heading: 'Common Sayan booking types', bullets: [
        'Honeymoon dinner (5-course tasting + sommelier) — see /honeymoon-chef',
        'Long-stay villa renter weekly meal-prep',
        'Vegan + plant-based tasting menus for wellness travellers',
        'Modern Balinese tasting menus with Tegallalang produce',
        'Family multi-day private chef placement (4+ nights)',
      ]},
      { heading: 'Pricing in Sayan', body: 'Same as Ubud base rate — from Rp 800,000 per hour, 3-hour minimum + ingredients at cost. Premium tasting menus typically Rp 6.5M-9M for 6 guests all-in. WhatsApp +62 822-3756-5997.' },
    ],
    ctaSource: 'cityHero',
    ctaPresetOpts: { city: 'Sayan, Ubud' },
    ctaLabel: 'WhatsApp for a Sayan chef',
    secondaryCta: { label: 'See Ubud page', href: '/ubud' },
    structuredData: [
      ...baseSchema('sayan-private-chef', 'Private Chef in Sayan, Ubud — Ayung River Villa Dining | myCHEF', 'Background-checked private chef for Sayan villas in Ubud.', 'Sayan'),
      { '@context': 'https://schema.org', '@type': 'Service', '@id': 'https://mychef.id/sayan-private-chef#service', name: 'Private Chef in Sayan, Ubud, Bali', serviceType: 'Private chef and in-villa dining in Sayan', provider: { '@id': 'https://mychef.id/#organization' } },
    ],
  },

  'padang-padang-private-chef': {
    slug: 'padang-padang-private-chef',
    canonical: 'https://mychef.id/padang-padang-private-chef',
    title: 'Private Chef in Padang Padang, Uluwatu — Beach Villa Dining | myCHEF',
    description: 'Background-checked private chef for Padang Padang villas in Uluwatu. Cliff-top + beach villas, Mediterranean grills, surf-trip catering. WhatsApp booking.',
    keywords: 'private chef padang padang, padang padang uluwatu chef, padang padang beach villa chef',
    h1: 'Private Chef in Padang Padang, Uluwatu',
    lead: "Padang Padang is the iconic Bukit beach — small white sand bay, world-class surf, the cliff-top villas above. The crowd is mixed: surf-trip groups, honeymooners at the cliff villas, beach-club lovers walking down the steps. myCHEF cooks Mediterranean grill menus and modern European tasting menus in Padang Padang villa kitchens regularly.",
    sections: [
      { heading: 'Why Padang Padang suits private chef dining', bullets: [
        'Cliff-top villas with infinity pools and ocean views — sunset dinner setting',
        'Beach access for cocktail hour before villa dinner service',
        'Outdoor villa kitchens — easy fit for Mediterranean grills + wood-fired mains',
        'World-class sunset (~18:30 local) lines up perfectly with first-course timing',
      ]},
      { heading: 'Common Padang Padang booking types', bullets: [
        'Surf-trip group dinners (8-15 guests, family-style Mediterranean)',
        'Honeymoon couple dinners — see /honeymoon-chef',
        'Cliff-top proposal dinners with sunset moment — see /proposal-dinner',
        'Multi-day private chef for villa renters staying 5+ nights',
      ]},
      { heading: 'Pricing in Padang Padang', body: 'Same as Uluwatu base rate — from Rp 800,000 per hour, 3-hour minimum + ingredients at cost. Small Bukit travel surcharge for remote cliff villas. WhatsApp +62 822-3756-5997.' },
    ],
    ctaSource: 'cityHero',
    ctaPresetOpts: { city: 'Padang Padang, Uluwatu' },
    ctaLabel: 'WhatsApp for a Padang Padang chef',
    secondaryCta: { label: 'See Uluwatu page', href: '/uluwatu' },
    structuredData: [
      ...baseSchema('padang-padang-private-chef', 'Private Chef in Padang Padang, Uluwatu — Beach Villa Dining | myCHEF', 'Background-checked private chef for Padang Padang villas.', 'Padang Padang'),
      { '@context': 'https://schema.org', '@type': 'Service', '@id': 'https://mychef.id/padang-padang-private-chef#service', name: 'Private Chef in Padang Padang, Uluwatu, Bali', serviceType: 'Private chef and in-villa dining in Padang Padang', provider: { '@id': 'https://mychef.id/#organization' } },
    ],
  },

  'pererenan-private-chef': {
    slug: 'pererenan-private-chef',
    canonical: 'https://mychef.id/pererenan-private-chef',
    title: 'Private Chef in Pererenan, Canggu — Rice-Field Villa Dining | myCHEF',
    description: 'Background-checked private chef for Pererenan villas in Canggu. Rice-field villas, Mediterranean + plant-based menus, surf+wellness crowd. WhatsApp booking.',
    keywords: 'private chef pererenan, pererenan canggu villa chef, pererenan vegan chef',
    h1: 'Private Chef in Pererenan, Canggu',
    lead: 'Pererenan is the quieter rice-field neighbor of Canggu — recently exploded with new luxury villas, organic cafés, and laid-back surf-and-wellness lifestyle. The crowd skews longer-stay than Berawa or Echo Beach. myCHEF cooks Mediterranean + plant-based menus in Pererenan villas regularly, including weekly meal-prep contracts for long-stay residents.',
    sections: [
      { heading: 'Why Pererenan suits private chef dining', bullets: [
        'Quieter than Berawa or Echo Beach — restaurant trips are a 10-min drive, private chef is the easier option',
        'New luxury villas with high-grade kitchens — full equipment for tasting menus',
        'Wellness-leaning crowd — vegan, anti-inflammatory, organic-forward menus dominate',
        'Direct relationships with Pererenan and Tegallalang organic farms — freshest possible produce',
      ]},
      { heading: 'Common Pererenan booking types', bullets: [
        'Long-stay digital nomad weekly meal-prep — see /services/weekly-meal-prep',
        'Vegan + plant-based villa dinners — see /menus/vegan',
        'Mediterranean grill dinners on the villa terrace',
        'Birthday + anniversary dinners with photographer coordination',
        'Yoga retreat catering at Pererenan retreat venues — see /retreats',
      ]},
      { heading: 'Pricing in Pererenan', body: 'Same as Canggu — from Rp 800,000 per hour, 3-hour minimum + ingredients at cost. No travel fee. Weekly meal-prep contracts (1-3 sessions/week) start at Rp 2.5M per session. WhatsApp +62 822-3756-5997.' },
    ],
    ctaSource: 'cityHero',
    ctaPresetOpts: { city: 'Pererenan, Canggu' },
    ctaLabel: 'WhatsApp for a Pererenan chef',
    secondaryCta: { label: 'See Canggu page', href: '/canggu' },
    structuredData: [
      ...baseSchema('pererenan-private-chef', 'Private Chef in Pererenan, Canggu — Rice-Field Villa Dining | myCHEF', 'Background-checked private chef for Pererenan villas in Canggu.', 'Pererenan'),
      { '@context': 'https://schema.org', '@type': 'Service', '@id': 'https://mychef.id/pererenan-private-chef#service', name: 'Private Chef in Pererenan, Canggu, Bali', serviceType: 'Private chef and in-villa dining in Pererenan', provider: { '@id': 'https://mychef.id/#organization' } },
    ],
  },

  'sanur-beach-private-chef': {
    slug: 'sanur-beach-private-chef',
    canonical: 'https://mychef.id/sanur-beach-private-chef',
    title: 'Private Chef in Sanur Beach — Family Villa Dining in Bali | myCHEF',
    description: 'Background-checked private chef for Sanur beach villas. Family-friendly dining, Asian fusion + Balinese menus, calm beach setting. WhatsApp booking.',
    keywords: 'private chef sanur, sanur villa chef, sanur beach dinner, family chef bali sanur',
    h1: 'Private Chef in Sanur Beach',
    lead: 'Sanur is Bali\'s family-friendly classic — calm reef-protected beach, traditional Balinese fishing village atmosphere, expat retiree community, longest-running international hotels (Bali\'s first major resort area, 1960s). myCHEF cooks family-style sharing menus and traditional Balinese feasts in Sanur villas regularly.',
    sections: [
      { heading: 'Why Sanur suits family + multi-generational dining', bullets: [
        'Calm sea, kid-safe beach — families travel here specifically',
        'Walkable beachfront — guests prefer relaxed family-style dinners over rigid plated courses',
        'Mature villa kitchens (most Sanur villas are 10+ years old, well-equipped)',
        'Strong Balinese + Indonesian cultural identity — traditional rijsttafel feasts feel right here',
      ]},
      { heading: 'Common Sanur booking types', bullets: [
        'Multi-generational family dinners (kids + grandparents at the same table)',
        'Traditional Balinese rijsttafel feasts — see /menus/balinese',
        'Asian fusion family-style sharing — see /menus/asian-fusion',
        'Long-stay expat weekly meal-prep — see /services/weekly-meal-prep',
        'Birthday celebrations with kid-friendly menu adaptation',
      ]},
      { heading: 'Pricing in Sanur', body: 'Same as base rate — from Rp 800,000 per hour, 3-hour minimum + ingredients at cost. No travel fee. Family rijsttafel feasts for 6-10 guests typically Rp 4.8M-6M all-in. WhatsApp +62 822-3756-5997.' },
    ],
    ctaSource: 'cityHero',
    ctaPresetOpts: { city: 'Sanur Beach' },
    ctaLabel: 'WhatsApp for a Sanur Beach chef',
    secondaryCta: { label: 'See Sanur page', href: '/sanur' },
    structuredData: [
      ...baseSchema('sanur-beach-private-chef', 'Private Chef in Sanur Beach — Family Villa Dining in Bali | myCHEF', 'Background-checked private chef for Sanur beach villas.', 'Sanur Beach'),
      { '@context': 'https://schema.org', '@type': 'Service', '@id': 'https://mychef.id/sanur-beach-private-chef#service', name: 'Private Chef in Sanur Beach, Bali', serviceType: 'Private chef and in-villa dining in Sanur', provider: { '@id': 'https://mychef.id/#organization' } },
    ],
  },

  'penestanan-private-chef': {
    slug: 'penestanan-private-chef',
    canonical: 'https://mychef.id/penestanan-private-chef',
    title: 'Private Chef in Penestanan, Ubud — Rice-Field Villa Dining | myCHEF',
    description: 'Background-checked private chef for Penestanan villas in Ubud. Rice-field views, vegan + Balinese tasting menus, wellness retreat catering. WhatsApp booking.',
    keywords: 'private chef penestanan, penestanan ubud villa chef, ubud penestanan dinner, penestanan vegan chef',
    h1: 'Private Chef in Penestanan, Ubud',
    lead: 'Penestanan is Ubud\'s expat-creative neighborhood — stepped rice-field villas, footpaths between rice paddies, yoga retreats hidden in the jungle. The crowd is wellness-forward, mostly long-stay expats and yoga teachers. myCHEF cooks vegan + Balinese tasting menus here regularly.',
    sections: [
      { heading: 'Why Penestanan suits private chef dining', bullets: [
        'Open-air villa kitchens facing rice fields — outdoor cooking + outdoor dining is the default',
        'Wellness-focused crowd — vegan, vegetarian, anti-inflammatory menus dominate',
        'Quiet rural setting — restaurants are a 20-min walk away, so private chef cooking is genuinely the easier option',
        'Local Tegallalang and Penestanan organic farms supply the freshest ingredients in Bali',
      ]},
      { heading: 'Common Penestanan booking types', bullets: [
        'Expat family weekly meal-prep — see /services/weekly-meal-prep',
        'Yoga teacher training catering (10-30 days, 3 meals/day) — see /retreats',
        'Vegan villa dinners — see /menus/vegan',
        'Modern Balinese tasting menus — see /menus/balinese',
        'Long-term resident chef placements (full-time household chef)',
      ]},
      { heading: 'Pricing in Penestanan', body: 'Same as Ubud base rate — from Rp 800,000 per hour, 3-hour minimum + ingredients at cost. No travel fee for Penestanan villas. Multi-day retreat catering has tiered pricing — see /retreats. WhatsApp +62 822-3756-5997.' },
    ],
    ctaSource: 'cityHero',
    ctaPresetOpts: { city: 'Penestanan, Ubud' },
    ctaLabel: 'WhatsApp for a Penestanan chef',
    secondaryCta: { label: 'See Ubud page', href: '/ubud' },
    structuredData: [
      ...baseSchema('penestanan-private-chef', 'Private Chef in Penestanan, Ubud — Rice-Field Villa Dining | myCHEF', 'Background-checked private chef for Penestanan villas in Ubud.', 'Penestanan'),
      {
        '@context': 'https://schema.org',
        '@type': 'Service',
        '@id': 'https://mychef.id/penestanan-private-chef#service',
        name: 'Private Chef in Penestanan, Ubud, Bali',
        serviceType: 'Private chef and in-villa dining in Penestanan',
        provider: { '@id': 'https://mychef.id/#organization' },
      },
    ],
  },

  'menus/halal': {
    slug: 'menus/halal',
    canonical: 'https://mychef.id/menus/halal',
    title: 'Halal Private Chef Menu in Bali — Certified Menus | myCHEF Indonesia',
    description: 'Halal-certified private chef menus in Bali. Modern Indonesian, Middle Eastern, Mediterranean halal options. All ingredients sourced from halal suppliers. From Rp 4.5M for 6 guests.',
    keywords: 'halal chef bali, halal private chef bali, halal catering bali, halal villa dinner bali, halal menu bali, muslim friendly chef bali',
    h1: 'Halal Private Chef Menu — Bali',
    lead: "myCHEF designs halal-certified menus for Muslim guests in Bali. All proteins are sourced from MUI-certified halal suppliers (Bali is a Hindu-majority island so this needs intentional supply-chain work — we have the relationships). The chef confirms supplier sourcing on every booking, separates cookware between halal and non-halal kitchens when both are needed for mixed groups, and avoids alcohol in cooking where requested.",
    sections: [
      { heading: 'Sample Halal Multi-Course Menu', body: 'Rp 5.4M for 6 guests, all-in (chef + halal-certified ingredients).', bullets: [
        'Starter — Mezze platter: hummus, baba ganoush, muhammara, charred flatbread, halal lamb kofta skewer',
        'Soup — Harira: Moroccan tomato + lentil + slow-cooked halal lamb soup with cumin and coriander',
        'Main — Slow-roasted halal lamb shoulder, saffron rice, charred eggplant, pomegranate-yoghurt sauce',
        'Side — Fattoush salad with sumac, mint, pomegranate, fried sourdough',
        'Dessert — Baklava with rosewater syrup, pistachios, and Bali honey ice cream',
      ]},
      { heading: 'Sample Indonesian Halal Sharing Feast', body: 'Rp 4.5M for 6-8 guests, all-in.', bullets: [
        'Sharing cold — Gado-gado, urap, kerupuk',
        'Sharing hot — Ayam goreng (halal chicken), ikan bakar (grilled fish), beef rendang, sayur asem',
        'Sides — Nasi kuning, sambal trio (matah, terasi, hijau)',
        'Dessert — Es campur, klepon, dadar gulung',
      ]},
      { heading: 'How we guarantee halal preparation', bullets: [
        'All meat sourced from MUI-certified halal suppliers in Bali (we have a vetted list of 4 suppliers covering chicken, beef, lamb, fish)',
        'For mixed groups (halal + non-halal guests), we run two kitchens or two sittings — never cross-contaminate',
        'No alcohol in cooking unless explicitly requested; mock-tail menu available',
        'Knife and cutting board separation maintained throughout service',
        'Chef confirms each ingredient\'s halal status with the booking party before final menu lock',
      ]},
    ],
    ctaSource: 'experience',
    ctaPresetOpts: { message: "Hi myCHEF — need a halal-certified private chef menu in Bali. Date: [date], [N] guests, area: [area], dietary specifics: [...]." },
    ctaLabel: 'WhatsApp for a halal menu',
    structuredData: [
      ...baseSchema('menus/halal', 'Halal Private Chef Menu in Bali — Certified Menus | myCHEF Indonesia', 'Halal-certified private chef menus in Bali.', 'Halal'),
      {
        '@context': 'https://schema.org',
        '@type': 'Menu',
        '@id': 'https://mychef.id/menus/halal#menu',
        name: 'Halal Certified Sample Menu',
        hasMenuSection: [
          { '@type': 'MenuSection', name: 'Halal Multi-Course Menu — Rp 5.4M for 6 guests', hasMenuItem: [
            { '@type': 'MenuItem', name: 'Starter', description: 'Mezze platter with halal lamb kofta' },
            { '@type': 'MenuItem', name: 'Soup', description: 'Harira — Moroccan halal lamb soup' },
            { '@type': 'MenuItem', name: 'Main', description: 'Slow-roasted halal lamb shoulder, saffron rice' },
            { '@type': 'MenuItem', name: 'Side', description: 'Fattoush salad' },
            { '@type': 'MenuItem', name: 'Dessert', description: 'Baklava with rosewater syrup, Bali honey ice cream' },
          ]},
        ],
      },
    ],
  },
};
